### ISSUE TITLE
Move controllers to controller runtime

### ISSUE THREAD

**Issue by alexander-demichev** [rancher/elemental-operator#177]
Moving controllers to controller runtime this will allow us to leverage usage of the kubebuilder https://book.kubebuilder.io/introduction.html, making the code cleaner, scalable, and well tested.

- [ ] Create an API directory to separate the old code from the new one. https://github.com/rancher/elemental-operator/pull/174
- [ ] Implement new main.go that will initialize new controllers https://github.com/rancher/elemental-operator/pull/174
- [ ] Wrap machine registration controller code with controller runtime and add tests https://github.com/rancher/elemental-operator/pull/174
- [ ]Wrap machine selector controller code with controller runtime and add tests https://github.com/rancher/elemental-operator/pull/174
- [ ] Wrap machine inventory controller code with controller runtime and add tests https://github.com/rancher/elemental-operator/pull/174
- [ ]Wrap manage os image controller code with controller runtime and add tests
- [ ] Wrap managed os version controller code with controller runtime and add tests
- [ ] Add new make tasks for generating CRD and RBAC from code https://github.com/rancher/elemental-operator/pull/174
- [ ] Find a way to run syncer and registration server together with the new stuff
- [ ] Make sure all e2e tests pass

All references to WIP PR will be replaced with smaller issues/PRs.

**Comment by davidcassany** [comment]
I consider this card completed. All essentials are already done. Further changes if needed or bugs should be tracked in specific issues. The kubebuilder version of elemental-operator is already merged to main and it passed manual and automated tests.
