### ISSUE TITLE
[Epic] build-image API: implement the build job

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-operator#336]
It should be performed in a separate pod, spawned on demand.
Should use a storage volume (emptyDir?)

**Comment by fgiudici** [comment]
- [ ] https://github.com/rancher/elemental-operator/issues/355
- [ ] https://github.com/rancher/elemental-operator/issues/356
- [ ] https://github.com/rancher/elemental-operator/issues/357
