### ISSUE TITLE
Prepare elemental operator v1.6.4 release

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-operator#740]
Request and document the required projects for the server side of elemental-operator build against Micro 6 (v1.6). Projects setup should be documented in Confluence.
- [x] Staging up to date and prepared for testing.
- [x] IBS Devel project up to date (Devel:Elemental:Marble)
- [x] Submission to release project in IBS

## Required submissions for elemental-operator v1.6

To ALP Pool:
- [x] elemental-operator

To Elemental product:
- [x] elemental-operator-crds-helm
- [x] elemental-operator-helm
- [x] operator-image
- [x] seedimage-builder
- [x] elemental-channel-image
- [x] ⚠ DROP ⚠ elemental-rt-channel-image (all channel flavors are part of `elemental-channel-image` now)

## Maintenance updates

To ALP Pool
- [x] systemd-presets-branding-Elemental rancher/elemental-operator#811
- [x] elemental-toolkit rancher/elemental-toolkit#2096

To Marble
- [x] OS/ISO images rancher/elemental#1455 and new patch level tag

To Elemental product
- [x] ⚠ elemental-channel-image (new OS image builds are not automatically referenced in channel, this requires manual update and a resubmission a posteriori)

**Comment by davidcassany** [comment]
Already drafted a document, but waiting maintenance to get some feedback for the expected IBS setup.

**Comment by kkaempf** [comment]
Preparation completed
- all client-side updates got accepted into `SUSE:ALP:Source:Standard:1.0`
- all server-side updates are submitted to `products/Elemental#1.6`
